fix py3 syntax errors in setup.py
Before this commit, attempted installation under Python 3 resulted in

```
$ pip install .
Processing /home/mambocab/cstar_src/ssl
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-i70f75bv-build/setup.py", line 33
        print 'looking for', f
                          ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
```

After it, attempted installation under Python 3 is the same as under
Python 2.6.0+:

```
$ pip install .
Processing /home/mambocab/cstar_src/ssl
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-149_ydsx-build/setup.py", line 14, in <module>
        + "or earlier.")
    ValueError: This extension should not be used with Python 2.6 or later (already built in), and has not been tested with Python 2.3.4 or earlier.

    ----------------------------------------
```